# Exercise 10-02 v1.2.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
  namespace: app
  labels:
    app: app-app
    tier: appserver
spec:
  selector:
    pod: app-pod
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
