# Exercise 32-05 v3.2.0
#
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db01-pv 
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/postgresql/data"
