# Exercise 32-05 v3.2.0
#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db01-pvc 
  namespace: db-ns
  labels:
    app: db01-db
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
